modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="diamondchest"
version="${file.jarVersion}"
displayName="Diamond Chest"
logoFile="assets/diamondchest/logo.png"
credits=""
authors="Will BL"
description='''
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
